name: goldens
description: Goldens for AngularDart.
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  js: ^0.6.7
  meta: ^1.11.0
  ngdart:
    git:
      url: git@github.com:darkstarx/angular.git
      path: ngdart
      ref: dev

dev_dependencies:
  build_runner: ^2.4.7
  build_web_compilers: ^4.0.7
  dart_style: ^2.3.4
  glob: ^2.1.2
  lints: ^3.0.0
  path: ^1.8.3
