name: ngforms
description: >
  Forms framework for AngularDart. Easily create forms to accept input from
  users.
version: 5.0.0-dev.2
repository: https://github.com/angulardart-community/angular

publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  ngdart:
    git:
      url: git@github.com:darkstarx/angular.git
      path: ngdart
      ref: dev

dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^2.2.1
  build_web_compilers: ^4.0.7
  lints: ^3.0.0
  mockito: ^5.4.3
  ngtest:
    git:
      url: git@github.com:darkstarx/angular.git
      path: ngtest
      ref: dev
  test: ^1.24.9
